services:
  db-postgres:
      # su postgres && psql -d casdoor -U pg-casdoor-username
      image: qpod/postgres-16-ext
      container_name: db-postgres
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  svc-jupyter:
      image: quay.io/jupyter/minimal-notebook
      depends_on:
        - db-postgres
      container_name: dev-jupyter
      hostname: jupyter
      user: root
      environment:
        NB_USER: root
        NB_UID: 0
        NB_GID: 0
      ports:
        - 8888:8888
      volumes:
        - "./:/home/root/work"
      command: ["start-notebook.py", "--allow-root"]
      ## docker logs dev-jupyter 2>&1|grep token=
